/**
 * NOTE: This class is auto generated by the swagger code generator program (3.0.36).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.CardType;
import io.swagger.model.CghspayScaleBean;
import io.swagger.model.Payscale;
import io.swagger.model.ValidationErrorPayScale;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.responses.ApiResponses;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestHeader;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.RequestPart;
import org.springframework.web.multipart.MultipartFile;
import org.springframework.web.bind.annotation.CookieValue;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "io.swagger.codegen.v3.generators.java.SpringCodegen", date = "2023-01-18T12:17:29.581Z[GMT]")
@Validated
public interface CardTypeApi {

    @Operation(summary = "create a onboarding payscale", description = "", tags={ "payscale" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "Successful operation", content = @Content(mediaType = "application/json", schema = @Schema(implementation = Payscale.class))),
        
        @ApiResponse(responseCode = "405", description = "Validation exception", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ValidationErrorPayScale.class))) })
    @RequestMapping(value = "/CardType",
        produces = { "application/json" }, 
        consumes = { "application/json" }, 
        method = RequestMethod.POST)
    ResponseEntity<CardType> post(@Parameter(in = ParameterIn.DEFAULT, description = "To create a new Onboarding payscale", required=true, schema=@Schema()) @Valid @RequestBody Payscale body);


    @Operation(summary = "Returns payscale", description = "", tags={ "payscale" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Payscale.class)))) })
    @RequestMapping(value = "/CardType",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<List<CardType>> list();
    
    
    @Operation(summary = "Returns payscale Name using id", description = "", tags={ "Payscale" })
    @ApiResponses(value = { 
        @ApiResponse(responseCode = "200", description = "successful operation", content = @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = Payscale.class)))) })
    @RequestMapping(value = "/CardType/{id}",
        produces = { "application/json" }, 
        method = RequestMethod.GET)
    ResponseEntity<CardType> get(@PathVariable long id);

}

